ERROR - 2024-03-22 18:44:04,994
Function: paging
Message:
Traceback (most recent call last):
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 80, in paging
    s.agency.agency_process(agency)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 73, in agency_process
    current_agency.alerts(non_agency_calls)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/incidents.py", line 630, in alerts
    units = self.units.get(callid)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/units.py", line 201, in get
    response = urlopen(api)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


ERROR - 2024-03-22 18:44:05,540
Function: paging
Message:
Traceback (most recent call last):
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 80, in paging
    s.agency.agency_process(agency)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 67, in agency_process
    non_agency_calls = current_agency.other()
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/incidents.py", line 101, in other
    return calls
UnboundLocalError: local variable 'calls' referenced before assignment


ERROR - 2024-03-22 18:49:42,779
Function: paging
Message:
Traceback (most recent call last):
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 80, in paging
    s.agency.agency_process(agency)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 73, in agency_process
    current_agency.alerts(non_agency_calls)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/incidents.py", line 630, in alerts
    units = self.units.get(callid)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/units.py", line 201, in get
    response = urlopen(api)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


ERROR - 2024-03-22 18:53:42,922
Function: paging
Message:
Traceback (most recent call last):
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 80, in paging
    s.agency.agency_process(agency)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 73, in agency_process
    current_agency.alerts(non_agency_calls)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/incidents.py", line 630, in alerts
    units = self.units.get(callid)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/units.py", line 201, in get
    response = urlopen(api)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


ERROR - 2024-03-22 18:54:10,712
Function: paging
Message:
Traceback (most recent call last):
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 82, in paging
    s.agency.agency_process(agency)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/agency.py", line 75, in agency_process
    current_agency.alerts(non_agency_calls)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/incidents.py", line 632, in alerts
    units = self.units.get(callid)
  File "/mnt/analytics/home/lhaynie/spillman-automation/DEV-196/spillman/units.py", line 201, in get
    response = urlopen(api)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


